development:
  adapter: postgres
  database: wakame_dcmgr_gui
  host: localhost
  user: wakame_dcmgr_gui
  password: passwd

test:
  adapter: postgres
  database: wakame_dcmgr_gui
  host: localhost
  user: wakame_dcmgr_gui
  password: passwd

production:
  adapter: postgres
  database: wakame_dcmgr_gui
  host: localhost
  user: wakame_dcmgr_gui
  password: passwd
